/**
 * @file mbr_dbc.h
 *
 * @brief This header file was generated by cantools version 42.0.3 Wed Jul  8 16:02:45 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef MBR_DBC_H
#define MBR_DBC_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define MBR_DBC_RPM_DATA_FRAME_ID (0x100u)
#define MBR_DBC_F_SHOCK_DATA_FRAME_ID (0x200u)
#define MBR_DBC_R_SHOCK_DATA_FRAME_ID (0x201u)
#define MBR_DBC_BUS_HALT_ALL_FRAME_ID (0x01u)
#define MBR_DBC_BUS_START_ALL_FRAME_ID (0x02u)
#define MBR_DBC_BUS_START_RPM_FRAME_ID (0x03u)
#define MBR_DBC_BUS_START_SHOCK_FRAME_ID (0x04u)

/* Frame lengths in bytes. */
#define MBR_DBC_RPM_DATA_LENGTH (8u)
#define MBR_DBC_F_SHOCK_DATA_LENGTH (8u)
#define MBR_DBC_R_SHOCK_DATA_LENGTH (8u)
#define MBR_DBC_BUS_HALT_ALL_LENGTH (1u)
#define MBR_DBC_BUS_START_ALL_LENGTH (1u)
#define MBR_DBC_BUS_START_RPM_LENGTH (1u)
#define MBR_DBC_BUS_START_SHOCK_LENGTH (1u)

/* Extended or standard frame types. */
#define MBR_DBC_RPM_DATA_IS_EXTENDED (0)
#define MBR_DBC_F_SHOCK_DATA_IS_EXTENDED (0)
#define MBR_DBC_R_SHOCK_DATA_IS_EXTENDED (0)
#define MBR_DBC_BUS_HALT_ALL_IS_EXTENDED (0)
#define MBR_DBC_BUS_START_ALL_IS_EXTENDED (0)
#define MBR_DBC_BUS_START_RPM_IS_EXTENDED (0)
#define MBR_DBC_BUS_START_SHOCK_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define MBR_DBC_BUS_HALT_ALL_BUS_HALT_ALL_HALT_CONFIRMED_CHOICE (255u)

#define MBR_DBC_BUS_START_ALL_BUS_START_ALL_START_ALL_CONFIRMED_CHOICE (255u)

#define MBR_DBC_BUS_START_RPM_BUS_START_RPM_RPM_START_CONFIRMED_CHOICE (255u)

#define MBR_DBC_BUS_START_SHOCK_BUS_START_SHOCK_SHOCK_START_CONFIRMED_CHOICE (255u)

/* Frame Names. */
#define MBR_DBC_RPM_DATA_NAME "RPM_DATA"
#define MBR_DBC_F_SHOCK_DATA_NAME "F_SHOCK_DATA"
#define MBR_DBC_R_SHOCK_DATA_NAME "R_SHOCK_DATA"
#define MBR_DBC_BUS_HALT_ALL_NAME "BUS_HALT_ALL"
#define MBR_DBC_BUS_START_ALL_NAME "BUS_START_ALL"
#define MBR_DBC_BUS_START_RPM_NAME "BUS_START_RPM"
#define MBR_DBC_BUS_START_SHOCK_NAME "BUS_START_SHOCK"

/* Signal Names. */
#define MBR_DBC_RPM_DATA_ENGINE_RPM_NAME "EngineRPM"
#define MBR_DBC_RPM_DATA_WHEEL_RPM_NAME "WheelRPM"
#define MBR_DBC_F_SHOCK_DATA_FR_SHOCK_NAME "FR_Shock"
#define MBR_DBC_F_SHOCK_DATA_FL_SHOCK_NAME "FL_Shock"
#define MBR_DBC_R_SHOCK_DATA_RL_SHOCK_NAME "RL_Shock"
#define MBR_DBC_R_SHOCK_DATA_RR_SHOCK_NAME "RR_Shock"
#define MBR_DBC_BUS_HALT_ALL_BUS_HALT_ALL_NAME "BUS_HALT_ALL"
#define MBR_DBC_BUS_START_ALL_BUS_START_ALL_NAME "BUS_START_ALL"
#define MBR_DBC_BUS_START_RPM_BUS_START_RPM_NAME "BUS_START_RPM"
#define MBR_DBC_BUS_START_SHOCK_BUS_START_SHOCK_NAME "BUS_START_SHOCK"

/**
 * Signals in message RPM_DATA.
 *
 * Sends both wheel and engine RPM
 *
 * All signal values are as on the CAN bus.
 */
struct mbr_dbc_rpm_data_t {
    /**
     * Range: 0..50000 (0..5000 -)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t engine_rpm;

    /**
     * Range: 0..50000 (0..5000 -)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t wheel_rpm;
};

/**
 * Signals in message F_SHOCK_DATA.
 *
 * All signal values are as on the CAN bus.
 */
struct mbr_dbc_f_shock_data_t {
    /**
     * Range: 0..5000 (0..50 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t fr_shock;

    /**
     * Range: 0..5000 (0..50 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t fl_shock;
};

/**
 * Signals in message R_SHOCK_DATA.
 *
 * All signal values are as on the CAN bus.
 */
struct mbr_dbc_r_shock_data_t {
    /**
     * Range: 0..5000 (0..50 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t rl_shock;

    /**
     * Range: 0..5000 (0..50 -)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t rr_shock;
};

/**
 * Signals in message BUS_HALT_ALL.
 *
 * All signal values are as on the CAN bus.
 */
struct mbr_dbc_bus_halt_all_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bus_halt_all;
};

/**
 * Signals in message BUS_START_ALL.
 *
 * All signal values are as on the CAN bus.
 */
struct mbr_dbc_bus_start_all_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bus_start_all;
};

/**
 * Signals in message BUS_START_RPM.
 *
 * All signal values are as on the CAN bus.
 */
struct mbr_dbc_bus_start_rpm_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bus_start_rpm;
};

/**
 * Signals in message BUS_START_SHOCK.
 *
 * All signal values are as on the CAN bus.
 */
struct mbr_dbc_bus_start_shock_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bus_start_shock;
};

/**
 * Pack message RPM_DATA.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mbr_dbc_rpm_data_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_rpm_data_t *src_p,
    size_t size);

/**
 * Unpack message RPM_DATA.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mbr_dbc_rpm_data_unpack(
    struct mbr_dbc_rpm_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPM_DATA.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mbr_dbc_rpm_data_init(struct mbr_dbc_rpm_data_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mbr_dbc_rpm_data_engine_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mbr_dbc_rpm_data_engine_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_rpm_data_engine_rpm_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_rpm_data_engine_rpm_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mbr_dbc_rpm_data_wheel_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mbr_dbc_rpm_data_wheel_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_rpm_data_wheel_rpm_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_rpm_data_wheel_rpm_is_in_phys_range(double value);

/**
 * Pack message F_SHOCK_DATA.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mbr_dbc_f_shock_data_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_f_shock_data_t *src_p,
    size_t size);

/**
 * Unpack message F_SHOCK_DATA.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mbr_dbc_f_shock_data_unpack(
    struct mbr_dbc_f_shock_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from F_SHOCK_DATA.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mbr_dbc_f_shock_data_init(struct mbr_dbc_f_shock_data_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mbr_dbc_f_shock_data_fr_shock_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mbr_dbc_f_shock_data_fr_shock_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_f_shock_data_fr_shock_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_f_shock_data_fr_shock_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mbr_dbc_f_shock_data_fl_shock_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mbr_dbc_f_shock_data_fl_shock_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_f_shock_data_fl_shock_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_f_shock_data_fl_shock_is_in_phys_range(double value);

/**
 * Pack message R_SHOCK_DATA.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mbr_dbc_r_shock_data_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_r_shock_data_t *src_p,
    size_t size);

/**
 * Unpack message R_SHOCK_DATA.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mbr_dbc_r_shock_data_unpack(
    struct mbr_dbc_r_shock_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from R_SHOCK_DATA.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mbr_dbc_r_shock_data_init(struct mbr_dbc_r_shock_data_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mbr_dbc_r_shock_data_rl_shock_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mbr_dbc_r_shock_data_rl_shock_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_r_shock_data_rl_shock_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_r_shock_data_rl_shock_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mbr_dbc_r_shock_data_rr_shock_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mbr_dbc_r_shock_data_rr_shock_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_r_shock_data_rr_shock_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_r_shock_data_rr_shock_is_in_phys_range(double value);

/**
 * Pack message BUS_HALT_ALL.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mbr_dbc_bus_halt_all_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_bus_halt_all_t *src_p,
    size_t size);

/**
 * Unpack message BUS_HALT_ALL.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mbr_dbc_bus_halt_all_unpack(
    struct mbr_dbc_bus_halt_all_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BUS_HALT_ALL.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mbr_dbc_bus_halt_all_init(struct mbr_dbc_bus_halt_all_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t mbr_dbc_bus_halt_all_bus_halt_all_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mbr_dbc_bus_halt_all_bus_halt_all_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_bus_halt_all_bus_halt_all_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_bus_halt_all_bus_halt_all_is_in_phys_range(double value);

/**
 * Pack message BUS_START_ALL.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mbr_dbc_bus_start_all_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_bus_start_all_t *src_p,
    size_t size);

/**
 * Unpack message BUS_START_ALL.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mbr_dbc_bus_start_all_unpack(
    struct mbr_dbc_bus_start_all_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BUS_START_ALL.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mbr_dbc_bus_start_all_init(struct mbr_dbc_bus_start_all_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t mbr_dbc_bus_start_all_bus_start_all_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mbr_dbc_bus_start_all_bus_start_all_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_bus_start_all_bus_start_all_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_bus_start_all_bus_start_all_is_in_phys_range(double value);

/**
 * Pack message BUS_START_RPM.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mbr_dbc_bus_start_rpm_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_bus_start_rpm_t *src_p,
    size_t size);

/**
 * Unpack message BUS_START_RPM.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mbr_dbc_bus_start_rpm_unpack(
    struct mbr_dbc_bus_start_rpm_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BUS_START_RPM.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mbr_dbc_bus_start_rpm_init(struct mbr_dbc_bus_start_rpm_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t mbr_dbc_bus_start_rpm_bus_start_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mbr_dbc_bus_start_rpm_bus_start_rpm_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_bus_start_rpm_bus_start_rpm_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_bus_start_rpm_bus_start_rpm_is_in_phys_range(double value);

/**
 * Pack message BUS_START_SHOCK.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mbr_dbc_bus_start_shock_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_bus_start_shock_t *src_p,
    size_t size);

/**
 * Unpack message BUS_START_SHOCK.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mbr_dbc_bus_start_shock_unpack(
    struct mbr_dbc_bus_start_shock_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BUS_START_SHOCK.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mbr_dbc_bus_start_shock_init(struct mbr_dbc_bus_start_shock_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t mbr_dbc_bus_start_shock_bus_start_shock_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mbr_dbc_bus_start_shock_bus_start_shock_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_bus_start_shock_bus_start_shock_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool mbr_dbc_bus_start_shock_bus_start_shock_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
