/**
 * @file mbr_dbc.c
 *
 * @brief This source file was generated by cantools version 42.0.3 Wed Jul  8 16:02:45 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "mbr_dbc.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int mbr_dbc_rpm_data_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_rpm_data_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->engine_rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->engine_rpm, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->wheel_rpm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->wheel_rpm, 8u, 0xffu);

    return (8);
}

int mbr_dbc_rpm_data_unpack(
    struct mbr_dbc_rpm_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->engine_rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->engine_rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->wheel_rpm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->wheel_rpm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int mbr_dbc_rpm_data_init(struct mbr_dbc_rpm_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mbr_dbc_rpm_data_t));

    return 0;
}

uint16_t mbr_dbc_rpm_data_engine_rpm_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double mbr_dbc_rpm_data_engine_rpm_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool mbr_dbc_rpm_data_engine_rpm_is_in_range(uint16_t value)
{
    return (value <= 50000u);
}

bool mbr_dbc_rpm_data_engine_rpm_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 5000.0));
}

uint16_t mbr_dbc_rpm_data_wheel_rpm_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double mbr_dbc_rpm_data_wheel_rpm_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool mbr_dbc_rpm_data_wheel_rpm_is_in_range(uint16_t value)
{
    return (value <= 50000u);
}

bool mbr_dbc_rpm_data_wheel_rpm_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 5000.0));
}

int mbr_dbc_f_shock_data_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_f_shock_data_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->fr_shock, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->fr_shock, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->fl_shock, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->fl_shock, 8u, 0xffu);

    return (8);
}

int mbr_dbc_f_shock_data_unpack(
    struct mbr_dbc_f_shock_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fr_shock = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->fr_shock |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->fl_shock = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->fl_shock |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int mbr_dbc_f_shock_data_init(struct mbr_dbc_f_shock_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mbr_dbc_f_shock_data_t));

    return 0;
}

uint16_t mbr_dbc_f_shock_data_fr_shock_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double mbr_dbc_f_shock_data_fr_shock_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool mbr_dbc_f_shock_data_fr_shock_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

bool mbr_dbc_f_shock_data_fr_shock_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 50.0));
}

uint16_t mbr_dbc_f_shock_data_fl_shock_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double mbr_dbc_f_shock_data_fl_shock_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool mbr_dbc_f_shock_data_fl_shock_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

bool mbr_dbc_f_shock_data_fl_shock_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 50.0));
}

int mbr_dbc_r_shock_data_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_r_shock_data_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rl_shock, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rl_shock, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->rr_shock, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->rr_shock, 8u, 0xffu);

    return (8);
}

int mbr_dbc_r_shock_data_unpack(
    struct mbr_dbc_r_shock_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rl_shock = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rl_shock |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->rr_shock = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->rr_shock |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int mbr_dbc_r_shock_data_init(struct mbr_dbc_r_shock_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mbr_dbc_r_shock_data_t));

    return 0;
}

uint16_t mbr_dbc_r_shock_data_rl_shock_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double mbr_dbc_r_shock_data_rl_shock_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool mbr_dbc_r_shock_data_rl_shock_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

bool mbr_dbc_r_shock_data_rl_shock_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 50.0));
}

uint16_t mbr_dbc_r_shock_data_rr_shock_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double mbr_dbc_r_shock_data_rr_shock_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool mbr_dbc_r_shock_data_rr_shock_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

bool mbr_dbc_r_shock_data_rr_shock_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 50.0));
}

int mbr_dbc_bus_halt_all_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_bus_halt_all_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bus_halt_all, 0u, 0xffu);

    return (1);
}

int mbr_dbc_bus_halt_all_unpack(
    struct mbr_dbc_bus_halt_all_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bus_halt_all = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int mbr_dbc_bus_halt_all_init(struct mbr_dbc_bus_halt_all_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mbr_dbc_bus_halt_all_t));

    return 0;
}

uint8_t mbr_dbc_bus_halt_all_bus_halt_all_encode(double value)
{
    return (uint8_t)(value);
}

double mbr_dbc_bus_halt_all_bus_halt_all_decode(uint8_t value)
{
    return ((double)value);
}

bool mbr_dbc_bus_halt_all_bus_halt_all_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool mbr_dbc_bus_halt_all_bus_halt_all_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int mbr_dbc_bus_start_all_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_bus_start_all_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bus_start_all, 0u, 0xffu);

    return (1);
}

int mbr_dbc_bus_start_all_unpack(
    struct mbr_dbc_bus_start_all_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bus_start_all = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int mbr_dbc_bus_start_all_init(struct mbr_dbc_bus_start_all_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mbr_dbc_bus_start_all_t));

    return 0;
}

uint8_t mbr_dbc_bus_start_all_bus_start_all_encode(double value)
{
    return (uint8_t)(value);
}

double mbr_dbc_bus_start_all_bus_start_all_decode(uint8_t value)
{
    return ((double)value);
}

bool mbr_dbc_bus_start_all_bus_start_all_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool mbr_dbc_bus_start_all_bus_start_all_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int mbr_dbc_bus_start_rpm_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_bus_start_rpm_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bus_start_rpm, 0u, 0xffu);

    return (1);
}

int mbr_dbc_bus_start_rpm_unpack(
    struct mbr_dbc_bus_start_rpm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bus_start_rpm = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int mbr_dbc_bus_start_rpm_init(struct mbr_dbc_bus_start_rpm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mbr_dbc_bus_start_rpm_t));

    return 0;
}

uint8_t mbr_dbc_bus_start_rpm_bus_start_rpm_encode(double value)
{
    return (uint8_t)(value);
}

double mbr_dbc_bus_start_rpm_bus_start_rpm_decode(uint8_t value)
{
    return ((double)value);
}

bool mbr_dbc_bus_start_rpm_bus_start_rpm_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool mbr_dbc_bus_start_rpm_bus_start_rpm_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int mbr_dbc_bus_start_shock_pack(
    uint8_t *dst_p,
    const struct mbr_dbc_bus_start_shock_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bus_start_shock, 0u, 0xffu);

    return (1);
}

int mbr_dbc_bus_start_shock_unpack(
    struct mbr_dbc_bus_start_shock_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bus_start_shock = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int mbr_dbc_bus_start_shock_init(struct mbr_dbc_bus_start_shock_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mbr_dbc_bus_start_shock_t));

    return 0;
}

uint8_t mbr_dbc_bus_start_shock_bus_start_shock_encode(double value)
{
    return (uint8_t)(value);
}

double mbr_dbc_bus_start_shock_bus_start_shock_decode(uint8_t value)
{
    return ((double)value);
}

bool mbr_dbc_bus_start_shock_bus_start_shock_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool mbr_dbc_bus_start_shock_bus_start_shock_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}
